export const PLANETS_INDEX_REQUESTED = "Planets/INDEX_REQUESTED";
export const PLANETS_INDEX_FAILED = "Planets/INDEX_FAILED";
export const PLANETS_INDEX_SUCCEEDED = "Planets/INDEX_SUCCEEDED";

export const PLANET_SELECTED = "Planet/SELECTED";

export const PLANET_RESIDENTS_GET_REQUESTED = "PlanetsResidents/GET_REQUESTED";
export const PLANET_RESIDENTS_GET_FAILED = "PlanetsResidents/GET_FAILED";
export const PLANET_RESIDENTS_GET_SUCCEEDED = "PlanetsResidents/GET_SUCCEEDED";

export const PLANET_GET_REQUESTED = "Planet/GET_REQUESTED";
export const PLANET_GET_FAILED = "Planet/GET_FAILED";
export const PLANET_GET_SUCCEEDED = "Planet/GET_SUCCEEDED";

export const PLANET_HOMEWORLD_SELECTED = "PlanetHomeworld/SELECTED";

export const PEOPLE_INDEX_REQUESTED = "People/INDEX_REQUESTED";
export const PEOPLE_INDEX_FAILED = "People/INDEX_FAILED";
export const PEOPLE_INDEX_SUCCEEDED = "People/INDEX_SUCCEEDED";

export const PERSON_SELECTED = "Person/SELECTED";

export const SPECIES_INDEX_REQUESTED = "Species/INDEX_REQUESTED";
export const SPECIES_INDEX_FAILED = "Species/INDEX_FAILED";
export const SPECIES_INDEX_SUCCEEDED = "Species/INDEX_SUCCEEDED";

export const SPECIES_SELECTED = "Species/SELECTED";
